# ================= DATABASE =================
spring.datasource.url=jdbc:postgresql://dpg-dac89gmq1p3s739i53q0-a/moneymanagerdb_7ypc?sslmode=require
spring.datasource.username=moneymanagerdb_7ypc_user
spring.datasource.password=v3mdaYNr1gGXw5HcIHTX2NoxkFQ1nO49

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=465
spring.mail.username=${BREVO_USER}
spring.mail.password=${BREVO_SMTP_KEY}

spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.starttls.required=false
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

app.mail.from=sahilkhurakte99@gmail.com